title: PSL(2,ℝ) and Hyperbolic Geometry
description: by Xinze Li — Formalizing the equivalence T¹ℍ ≅ PSL(2,ℝ) ≅ Isom⁺(ℍ²) in Lean 4
baseurl: ""
url: "https://Xinze-Li-Bryan.github.io/psl2r-formalization"
github_username: Xinze-Li-Bryan
repository: Xinze-Li-Bryan/psl2r-formalization
remote_theme: pages-themes/midnight@v0.2.0 
plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
